version: "3"

services:
  migration:
    image: ghcr.io/randomicu/fakedata-database:0.0.2
    env_file:
      - .env
    depends_on:
      - database
    networks:
      containers:
        ipv4_address: 172.19.0.99

  database:
    image: library/postgres:13-alpine
    restart: on-failure
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      containers:
        ipv4_address: 172.19.0.10

  server:
    image: ghcr.io/randomicu/fakedata-backend:latest
    depends_on:
      - migration
      - database
    ports:
    - 8000:8000
    env_file:
      - .env
    networks:
      containers:
        ipv4_address: 172.19.0.20

volumes:
  database-data:

networks:
  containers:
    external:
      name: containers
